import { Contract, ContractRunner, Interface, InterfaceAbi } from "ethers";

/** ABIs exported by `npm run export-abi` (and by every deploy). */
const abiModules = import.meta.glob("../contracts/abi/*.json", { eager: true }) as Record<
  string,
  { default: InterfaceAbi }
>;

/** Deployment files, one per chain id. A local deployment is regenerated by every stack start. */
const deploymentModules = import.meta.glob("../contracts/deployments/*.json", {
  eager: true,
}) as Record<string, { default: Deployment }>;

export interface Deployment {
  chainId: number;
  deployBlock: number;
  deployedAt: string;
  addresses: {
    vault: string;
    registry: string;
    book: string;
    verifier: string;
    planner: string;
    learning: string;
    engine: string;
  };
}

export type ContractName =
  | "Vault"
  | "TIESRegistry"
  | "PolicyBook"
  | "SignedAdapterVerifier"
  | "EscalationPlanner"
  | "LearningModule"
  | "SettlementEngine";

export function abiOf(name: ContractName): InterfaceAbi {
  const hit = Object.entries(abiModules).find(([path]) => path.endsWith(`/${name}.json`));
  if (!hit) throw new Error(`ABI for ${name} not found; run "npm run export-abi"`);
  return hit[1].default;
}

export function getDeployment(chainId: number | null | undefined): Deployment | null {
  if (chainId == null) return null;
  const hit = Object.entries(deploymentModules).find(([path]) => path.endsWith(`/${chainId}.json`));
  return hit ? hit[1].default : null;
}

export interface TiesContracts {
  vault: Contract;
  registry: Contract;
  book: Contract;
  engine: Contract;
  verifier: Contract;
}

export function connectContracts(d: Deployment, runner: ContractRunner): TiesContracts {
  const make = (address: string, name: ContractName) => new Contract(address, abiOf(name), runner);
  return {
    vault: make(d.addresses.vault, "Vault"),
    registry: make(d.addresses.registry, "TIESRegistry"),
    book: make(d.addresses.book, "PolicyBook"),
    engine: make(d.addresses.engine, "SettlementEngine"),
    verifier: make(d.addresses.verifier, "SignedAdapterVerifier"),
  };
}

/** Every interface the UI can decode custom errors and events with. */
export function allInterfaces(): { name: ContractName; iface: Interface }[] {
  const names: ContractName[] = [
    "SettlementEngine",
    "PolicyBook",
    "Vault",
    "TIESRegistry",
    "SignedAdapterVerifier",
  ];
  return names.map((name) => ({ name, iface: new Interface(abiOf(name)) }));
}
